servers:
  -
    host: host1 
    username: 
    password: 
    remote_dir: /var/log/filebar
    remote_dir_for_archived_log: /tmp
    local_dir: /home/user/parsa/logs/host1
  -
    host: host2 
    username: 
    password: 
    remote_dir: /var/log/filebar
    remote_dir_for_archived_log: /tmp
    local_dir: /home/user/parsa/logs/host2
