servers:
  -
    host: host1 
    username: 
    password: 
    remote_dir: /var/log/apache2
    local_dir: /mnt/src/parsa
  -
    host: host2 
    username: 
    password: 
    remote_dir: /var/log/apache21
    local_dir: /mnt/src/parsa1
